2022-01-01 16:01:01,863 INFO    MainThread:4624 [wandb_setup.py:_flush():71] setting env: {}
2022-01-01 16:01:01,863 INFO    MainThread:4624 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-01 16:01:01,863 INFO    MainThread:4624 [wandb_setup.py:_flush():71] setting login settings: {'mode': 'offline'}
2022-01-01 16:01:01,863 INFO    MainThread:4624 [wandb_init.py:_log_setup():371] Logging user logs to C:\university\Thesis\AGAIN-VC - Copy\wandb\offline-run-20220101_160101-3v6wdqmr\logs\debug.log
2022-01-01 16:01:01,863 INFO    MainThread:4624 [wandb_init.py:_log_setup():372] Logging internal logs to C:\university\Thesis\AGAIN-VC - Copy\wandb\offline-run-20220101_160101-3v6wdqmr\logs\debug-internal.log
2022-01-01 16:01:01,865 INFO    MainThread:4624 [wandb_init.py:init():404] calling init triggers
2022-01-01 16:01:01,865 INFO    MainThread:4624 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {'_name': 'train_again', 'writer': 'wandb', 'ckpt_dir': 'checkpoints/again', 'flag': 'c4s', 'dataset': {'dataset_name': 'vctk', 'feat_path': 'data/features/vctk', 'feat': ['mel'], 'indexes_path': './data/indexes/vctk/indexes.pkl', 'seglen': 128}, 'dataloader': {'train': {'batch_size': 32, 'shuffle': True}, 'dev': {'batch_size': 64}}, 'build': {'model_name': 'again', 'model': {'params': {'encoder_params': {'c_in': 80, 'c_h': 256, 'c_out': 4, 'n_conv_blocks': 6, 'subsample': [1, 1, 1, 1, 1, 1]}, 'decoder_params': {'c_in': 4, 'c_h': 256, 'c_out': 80, 'n_conv_blocks': 6, 'upsample': [1, 1, 1, 1, 1, 1]}, 'activation_params': {'act': 'sigmoid', 'params': {'alpha': 0.1}}}}, 'optimizer': {'params': {'lr': 0.0005, 'betas': [0.9, 0.999], 'amsgrad': True, 'weight_decay': 0.0001}, 'grad_norm': 3}}, '_args': Namespace(config='config/train_again-c4s.yaml', dry=False, debug=False, seed=1234567, load='', njobs=4, total_steps=100000, verbose_steps=10, log_steps=500, save_steps=5000, eval_steps=5000)}
2022-01-01 16:01:01,866 INFO    MainThread:4624 [wandb_init.py:init():460] starting backend
2022-01-01 16:01:01,866 INFO    MainThread:4624 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-01-01 16:01:01,872 INFO    MainThread:4624 [backend.py:ensure_launched():216] starting backend process...
2022-01-01 16:01:01,989 INFO    MainThread:4624 [backend.py:ensure_launched():221] started backend process with pid: 11164
2022-01-01 16:01:01,990 INFO    MainThread:4624 [wandb_init.py:init():469] backend started and connected
2022-01-01 16:01:01,999 INFO    MainThread:4624 [wandb_init.py:init():533] updated telemetry
2022-01-01 16:01:02,086 INFO    MainThread:4624 [wandb_init.py:init():606] starting run threads in backend
2022-01-01 16:01:04,706 INFO    MainThread:4624 [wandb_run.py:_console_start():1810] atexit reg
2022-01-01 16:01:04,714 INFO    MainThread:4624 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-01 16:01:04,715 INFO    MainThread:4624 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-01 16:01:04,716 INFO    MainThread:4624 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-01 16:01:04,717 INFO    MainThread:4624 [wandb_init.py:init():633] run started, returning control to user process
2022-01-01 16:19:40,529 INFO    MainThread:4624 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-01 16:19:40,531 INFO    MainThread:4624 [wandb_run.py:_restore():1752] restore
2022-01-01 16:19:42,038 ERROR   MainThread:4624 [wandb_run.py:_atexit_cleanup():1798] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1934, in _on_finish
    self.history._flush()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_run.py", line 1017, in _history_callback
    self._backend.interface.publish_history(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\interface\interface.py", line 496, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2597, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2638, in val_to_json
    item.bind_to_run(run, key, namespace, id_=i)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 2264, in bind_to_run
    super(Image, self).bind_to_run(run, key, step, id_)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\data_types.py", line 498, in bind_to_run
    raise ValueError(
ValueError: Media train/seen/Melspectrogram is invalid. Please remove invalid filename characters
